[server]
headless = true
enableCORS = true
enableXsrfProtection = false
allowRunOnSave = true
runOnSave = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
